CREATE DATABASE NEGOCIO
USE NEGOCIO

/*una empresa dedicada al comercio de productos requiere una base de datos relacional en la que tenga acceso a.
  productos clientes proveedores y ventas ademas reqiere de un programa en c# que le permita el acceso a la informacion sin tener que hacer 
  uso de al motor de base de datos 
  contrulla la base de datos y aplique el modelo de capas en dicho prollecto*/

  CREATE TABLE PROVEEDOR(
	DNI_PROVEEDOR INT,
	NOM_PROVEEDOR VARCHAR (30),
	DIR_PROVEEDOR VARCHAR(30),
	TEL_PROVEEDOR INT
	CONSTRAINT PKP PRIMARY KEY(DNI_PROVEEDOR)
  )

  CREATE TABLE CLIENTE(
	DNI_CLIENTE INT,
	NOM_CLIENTE VARCHAR(50),
	DIR_CLIENTE VARCHAR(30),
	TEL_CLIENTE INT
	CONSTRAINT PKC PRIMARY KEY (DNI_CLIENTE)
  )

  CREATE TABLE PRODUCTO(
	REF_PRODUCTO INT,
	NOM_PRODUCTO VARCHAR (50),
	FECHA_INGRESO DATE,
	CANTIDAD INT,
	PRECIO_COMPRA FLOAT,
	PRECIO_VENTA FLOAT,
	DNI_PROVEEDOR INT,
	CONSTRAINT PKPROD PRIMARY KEY(REF_PRODUCTO),
	CONSTRAINT FKP FOREIGN KEY(DNI_PROVEEDOR)
	REFERENCES PROVEEDOR(DNI_PROVEEDOR)
  )

  CREATE TABLE VENTA(
	NUM_VENTA INT IDENTITY,
	REF_PRODUCTO1 INT,
	MEDIO_PAGO VARCHAR(30)
	CONSTRAINT FKPROD FOREIGN KEY(REF_PRODUCTO1)
	REFERENCES PRODUCTO(REF_PRODUCTO)
  )
 

  SELECT NOM_PRODUCTO,NUM_VENTA,MEDIO_PAGO, REF_PRODUCTO FROM PRODUCTO INNER JOIN VENTA
  ON VENTA.REF_PRODUCTO1 = PRODUCTO .REF_PRODUCTO WHERE NUM_VENTA = 1
  
  SELECT * FROM PROVEEDOR