USE NEGOCIO

CREATE PROC INGRESAR_PROVEEDOR
@DNI_PROVEEDOR INT,
@NOM_PROVEEDOR VARCHAR(50),
@DIR_PROVEEDOR VARCHAR(50),
@TEL_PROVEEDOR INT
AS

INSERT INTO PROVEEDOR(DNI_PROVEEDOR,NOM_PROVEEDOR,DIR_PROVEEDOR,TEL_PROVEEDOR)
VALUES(@DNI_PROVEEDOR, @NOM_PROVEEDOR, @DIR_PROVEEDOR, @TEL_PROVEEDOR)

CREATE PROC INGRESAR_CLIENTE
@DNI_CLIENTE INT,
@NOM_CLIENTE VARCHAR(50),
@DIR_CLIENTE VARCHAR(30),
@TEL_CLIENTE INT
AS
INSERT INTO CLIENTE(DNI_CLIENTE, NOM_CLIENTE, DIR_CLIENTE, TEL_CLIENTE)
VALUES(@DNI_CLIENTE, @NOM_CLIENTE, @DIR_CLIENTE, @TEL_CLIENTE)

CREATE PROC INGRESAR_PRODUCTO
@REF_PRODUCTO INT,
@NOM_PROCUCTO VARCHAR(50),
@FECHA_INGRESO DATE,
@CANTIDAD INT,
@PRECIO_COMPRA FLOAT,
@PRECIO_VENTA FLOAT,
@DNI_PROVEEDOR INT
AS
INSERT INTO PRODUCTO(REF_PRODUCTO, NOM_PRODUCTO, FECHA_INGRESO, CANTIDAD, PRECIO_COMPRA, PRECIO_VENTA, DNI_PROVEEDOR)
VALUES(@REF_PRODUCTO, @NOM_PROCUCTO, @FECHA_INGRESO, @CANTIDAD, @PRECIO_COMPRA, @PRECIO_VENTA, @DNI_PROVEEDOR)

CREATE PROC HACER_VENTA
@REF_PRODUCTO1 INT,
@MEDIO_PAGO VARCHAR(30)
AS
INSERT INTO VENTA(REF_PRODUCTO1, MEDIO_PAGO)
VALUES(@REF_PRODUCTO1, @MEDIO_PAGO)