USE NEGOCIO

CREATE PROC INGRESAR_PROVEEDOR
@DNI_PROVEEDOR INT,
@NOM_PROVEEDOR VARCHAR(50),
@DIR_PROVEEDOR VARCHAR(50),
@TEL_PROVEEDOR INT
AS

INSERT INTO PROVEEDOR(DNI_PROVEEDOR,NOM_PROVEEDOR,DIR_PROVEEDOR,TEL_PROVEEDOR)
VALUES(@DNI_PROVEEDOR, @NOM_PROVEEDOR, @DIR_PROVEEDOR, @TEL_PROVEEDOR)

CREATE PROC INGRESAR_CLIENTE
@DNI_CLIENTE INT,
@NOM_CLIENTE VARCHAR(50),
@DIR_CLIENTE VARCHAR(30),
@TEL_CLIENTE INT
AS
INSERT INTO CLIENTE(DNI_CLIENTE, NOM_CLIENTE, DIR_CLIENTE, TEL_CLIENTE)
VALUES(@DNI_CLIENTE, @NOM_CLIENTE, @DIR_CLIENTE, @TEL_CLIENTE)

CREATE PROC INGRESAR_PRODUCTO
@REF_PRODUCTO INT,
@NOM_PROCUCTO VARCHAR(50),
@FECHA_INGRESO DATE,
@CANTIDAD INT,
@PRECIO_COMPRA FLOAT,
@PRECIO_VENTA FLOAT,
@DNI_PROVEEDOR INT
AS
INSERT INTO PRODUCTO(REF_PRODUCTO, NOM_PRODUCTO, FECHA_INGRESO, CANTIDAD, PRECIO_COMPRA, PRECIO_VENTA, DNI_PROVEEDOR)
VALUES(@REF_PRODUCTO, @NOM_PROCUCTO, @FECHA_INGRESO, @CANTIDAD, @PRECIO_COMPRA, @PRECIO_VENTA, @DNI_PROVEEDOR)

CREATE PROC HACER_VENTA
@REF_PRODUCTO1 INT,
@MEDIO_PAGO VARCHAR(30)
AS
INSERT INTO VENTA(REF_PRODUCTO1, MEDIO_PAGO)
VALUES(@REF_PRODUCTO1, @MEDIO_PAGO)

--------PROCEDIMIENTOS PARA CONSULTAR REGISTROS DE LAS TABLAS----------
CREATE PROC GET_PROVEEDOR
@DNI_PROVEEDOR INT
AS

SELECT * FROM PROVEEDOR WHERE DNI_PROVEEDOR = @DNI_PROVEEDOR

-------------------------------------------------------
CREATE PROC GET_CLIENTE
@DNI_CLIENTE INT
AS
SELECT * FROM CLIENTE WHERE DNI_CLIENTE = @DNI_CLIENTE

------------------------------------------------
CREATE PROC GET_PORODUCTO
@REF_PRODUCTO INT
AS
SELECT * FROM PRODUCTO WHERE REF_PRODUCTO = @REF_PRODUCTO
--------------------------------------------------------------
---PROCEDIMIENTO QUE ME CONSULTA UNA VENTA INCLUYENDO UN INNER JOIN PARA QUE ME TRAIGA DATOS DE LA VENTA Y DEL PRODUCTO 
CREATE PROC GET_VENTA
@NUM_VENTA INT
AS
SELECT NUM_VENTA, REF_PRODUCTO, PRECIO_VENTA, NOM_PRODUCTO,MEDIO_PAGO FROM PRODUCTO INNER JOIN VENTA
ON VENTA.REF_PRODUCTO1 = PRODUCTO .REF_PRODUCTO WHERE NUM_VENTA = @NUM_VENTA 

-----PROCEDIMIENTOS PARA ELIMINAR REGISTROS EXISTENTES DE LAS TABLAS 

CREATE PROC ELIMINAR_PROVEEDOR
@DNI_PROVEEDOR INT
AS
DELETE FROM PROVEEDOR WHERE DNI_PROVEEDOR = @DNI_PROVEEDOR

------------------------------------------------------
CREATE PROC ELIMINAR_CLIENTE
@DNI_CLIENTE INT
AS
DELETE FROM CLIENTE WHERE DNI_CLIENTE = @DNI_CLIENTE
-----------------------------------------------

CREATE PROC ELIMINAR_PRODUCTO
@REF_PRODUCTO INT
AS
DELETE FROM PRODUCTO WHERE REF_PRODUCTO = REF_PRODUCTO
------------------------------------------------------

CREATE PROC ELIMINAR_VENTA
@NUM_VENTA INT
AS
DELETE FROM VENTA WHERE NUM_VENTA = @NUM_VENTA